#!/bin/bash

# Đoạn mã Base64 đã được mã hóa (thay thế bằng chuỗi đầy đủ)
ENCODED_SCRIPT="IyEvYmluL2Jhc2gKCkVsZXZhdGUgdG8gcm9vdApzdWRvIHN1CgojIERvd25sb2FkIHRoZSBpcHY2LXByb3h5LXNlcnZlciBzY3JpcHQKd2dldCBodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vVGVtcG9yYWxpdGFzL2lwdjYtcHJveHktc2VydmVyL21hc3Rlci9pcHY2LXByb3h5LXNlcnZlci5zaCAmJiBjaG1vZCAreCBpcHY2LXByb3h5LXNlcnZlci5zaAoKIyBHZW5lcmF0ZSByYW5kb20gdXNlcm5hbWUgYW5kIHBhc3N3b3JkClVTRVJOQU1FPSQob3BlbnNzbCByYW5kIC1iYXNlNjQgMTIpClBBU1NXT1JEPSQob3BlbnNzbCByYW5kIC1iYXNlNjQgMTIpCgojIFJ1biB0aGUgaXB2Ni1wcm94eS1zZXJ2ZXIgc2NyaXB0IHdpdGggZ2VuZXJhdGVkIGNyZWRlbnRpYWxzCi4vaXB2Ni1wcm94eS1zZXJ2ZXIuc2ggLXMgNjQgLWMgMTAwIC11ICRVU0VSTkFNRSAtcCAkUEFTU1dPUkQgLXQgaHR0cCAtciAxMAoKIyBDaGVjayBpZiB0aGUgcHJveHkgbGlzdCBmaWxlIGV4aXN0cw=="

# Giải mã và lưu vào tệp tạm thời
echo $ENCODED_SCRIPT | base64 --decode > /tmp/temp_script.sh

# Thực thi tệp tạm thời
bash /tmp/temp_script.sh

# Xóa tệp tạm thời sau khi thực thi xong
rm /tmp/temp_script.sh
